export const movieList = {
  dates: {
    maximum: "2024-08-14",
    minimum: "2024-07-03",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      genre_ids: [28, 35, 878],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool \u0026 Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      popularity: 11132.622,
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      release_date: "2024-07-24",
      title: "Deadpool \u0026 Wolverine",
      video: false,
      vote_average: 7.893,
      vote_count: 1634,
    },
    {
      adult: false,
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      popularity: 3155.341,
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      release_date: "2024-06-20",
      title: "Despicable Me 4",
      video: false,
      vote_average: 7.364,
      vote_count: 817,
    },
    {
      adult: false,
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 2775.425,
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      release_date: "2024-06-11",
      title: "Inside Out 2",
      video: false,
      vote_average: 7.626,
      vote_count: 2307,
    },
    {
      adult: false,
      backdrop_path: "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
      genre_ids: [27, 878, 53],
      id: 762441,
      original_language: "en",
      original_title: "A Quiet Place: Day One",
      overview:
        "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
      popularity: 2383.665,
      poster_path: "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
      release_date: "2024-06-26",
      title: "A Quiet Place: Day One",
      video: false,
      vote_average: 6.952,
      vote_count: 1177,
    },
    {
      adult: false,
      backdrop_path: "/r7HV1rKdUus2gJNChswMtpjpPft.jpg",
      genre_ids: [16, 35, 12, 10751],
      id: 831815,
      original_language: "en",
      original_title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
      overview:
        "When Bikini Bottom is scooped from the ocean, scientific squirrel Sandy Cheeks and her pal SpongeBob SquarePants saddle up for Texas to save their town.",
      popularity: 1500.719,
      poster_path: "/30YnfZdMNIV7noWLdvmcJS0cbnQ.jpg",
      release_date: "2024-08-01",
      title: "Saving Bikini Bottom: The Sandy Cheeks Movie",
      video: false,
      vote_average: 6.262,
      vote_count: 103,
    },
    {
      adult: false,
      backdrop_path: "/tqSg1hHiSWhHAhnjDhhevaFGsP0.jpg",
      genre_ids: [28, 18],
      id: 1066262,
      original_language: "en",
      original_title: "The Convert",
      overview:
        "Munro, a soldier turned lay preacher, comes to New Zealand to minister to the first British colonists, but he is converted by the powerful chief Maianui to serve a different purpose.",
      popularity: 1200.129,
      poster_path: "/e5ZqqPlhKstzB4geibpZh38w7Pq.jpg",
      release_date: "2024-03-14",
      title: "The Convert",
      video: false,
      vote_average: 6.6,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/c3rwwFFVbkyEI6wPtpPd9lvovPW.jpg",
      genre_ids: [28, 36],
      id: 1311550,
      original_language: "en",
      original_title: "House of Ga'a",
      overview:
        "At the height of the Oyo Empire, the ferocious Bashorun Ga'a became more powerful than the kings he enthroned, only to be undone by his own blood.",
      popularity: 1162.823,
      poster_path: "/6yK9hmS641NMwRkR1wWAALWI34t.jpg",
      release_date: "2024-07-26",
      title: "House of Ga'a",
      video: false,
      vote_average: 5.963,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      popularity: 1121.305,
      poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
      release_date: "2024-04-30",
      title: "The Garfield Movie",
      video: false,
      vote_average: 7.214,
      vote_count: 711,
    },
    {
      adult: false,
      backdrop_path: "/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg",
      genre_ids: [27, 80, 9648],
      id: 1023922,
      original_language: "en",
      original_title: "MaXXXine",
      overview:
        "In 1980s Hollywood, adult film star and aspiring actress Maxine Minx finally gets her big break. But as a mysterious killer stalks the starlets of Hollywood, a trail of blood threatens to reveal her sinister past.",
      popularity: 924.266,
      poster_path: "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
      release_date: "2024-07-04",
      title: "MaXXXine",
      video: false,
      vote_average: 6.384,
      vote_count: 254,
    },
    {
      adult: false,
      backdrop_path: "/6Vbm2nHxHMlZZ199fmZtMytpFvK.jpg",
      genre_ids: [28, 53, 35, 18],
      id: 1309923,
      original_language: "es",
      original_title: "No negociable",
      overview:
        "Hostage negotiator Alan Bender is called to rescue the president from a kidnapping, only to find himself also mediating to save his wife and marriage.",
      popularity: 809.541,
      poster_path: "/bHQG4UsLMFCy91gfLAFRpnCOPdP.jpg",
      release_date: "2024-07-25",
      title: "Non Negotiable",
      video: false,
      vote_average: 6.0,
      vote_count: 58,
    },
    {
      adult: false,
      backdrop_path: "/w22yUH5pAZ3CcTjbw9GEzPd5wxs.jpg",
      genre_ids: [878, 35],
      id: 1242372,
      original_language: "zh",
      original_title: "从21世纪安全撤离",
      overview:
        'On Planet K, unknown to anyone on Earth, three teenagers chosen by fate can travel back and forth twenty years into the future by sneezing. In the face of a shocking plot to destroy the world, they have nothing but crystal-clear stupidity and single-digit combat power, so how can they transform into heroes and fight against the super-villainous villains who are intent on destroying the world? How can they turn into heroes and fight against the super baddest villains intent on destroying the world? The "King Bomb" brothers, who look like grown-ups but have minds like no other, will save the future on behalf of the K-Star!',
      popularity: 797.869,
      poster_path: "/nZQPbD7IEKWiUDK7s9GKHwqP88g.jpg",
      release_date: "2024-07-18",
      title: "Escape from the 21st Century",
      video: false,
      vote_average: 7.25,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
      genre_ids: [14, 12, 10751, 35],
      id: 974262,
      original_language: "en",
      original_title: "Descendants: The Rise of Red",
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      popularity: 785.674,
      poster_path: "/t9u9FWpKlZcp0Wz1qPeV5AIzDsk.jpg",
      release_date: "2024-07-11",
      title: "Descendants: The Rise of Red",
      video: false,
      vote_average: 7.021,
      vote_count: 233,
    },
    {
      adult: false,
      backdrop_path: "/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg",
      genre_ids: [16, 878, 28],
      id: 1209290,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part Three",
      overview:
        "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?",
      popularity: 754.387,
      poster_path: "/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
      release_date: "2024-07-16",
      title: "Justice League: Crisis on Infinite Earths Part Three",
      video: false,
      vote_average: 7.533,
      vote_count: 137,
    },
    {
      adult: false,
      backdrop_path: "/8yPSYhooj8nyBbmV3GVdLDwuE7e.jpg",
      genre_ids: [18, 10749],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "Lily overcomes a traumatic childhood to embark on a new life. A chance meeting with neurosurgeon Ryle sparks a connection but Lily begins to see sides of him that remind her of her parents' relationship.",
      popularity: 689.574,
      poster_path: "/tJSbiu7S5pqDnzH9weTW82bYbWu.jpg",
      release_date: "2024-08-07",
      title: "It Ends with Us",
      video: false,
      vote_average: 7.3,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
      genre_ids: [28, 35],
      id: 1048241,
      original_language: "en",
      original_title: "My Spy The Eternal City",
      overview:
        "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
      popularity: 668.646,
      poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
      release_date: "2024-07-18",
      title: "My Spy The Eternal City",
      video: false,
      vote_average: 6.732,
      vote_count: 213,
    },
    {
      adult: false,
      backdrop_path: "/pZFuow2rweIqyNHz6xZSxnLVmMc.jpg",
      genre_ids: [27],
      id: 1097150,
      original_language: "en",
      original_title: "Deliver Us",
      overview:
        "When a nun in a remote convent claims immaculate conception, the Vatican sends a team of priests to investigate, concerned about an ancient prophecy that a woman will give birth to twin boys: one the Messiah, the other the Antichrist.",
      popularity: 554.794,
      poster_path: "/uoKUTwvHvSVHWjSM4RhCh6rKL0U.jpg",
      release_date: "2023-08-30",
      title: "Deliver Us",
      video: false,
      vote_average: 5.5,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
      genre_ids: [27, 53],
      id: 646683,
      original_language: "en",
      original_title: "The Exorcism",
      overview:
        "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
      popularity: 549.696,
      poster_path: "/v4PgVcOne2sumkyOK8O7BKB9PWX.jpg",
      release_date: "2024-05-30",
      title: "The Exorcism",
      video: false,
      vote_average: 4.6,
      vote_count: 109,
    },
    {
      adult: false,
      backdrop_path: "/iAlsYg6dlv1fvOBypM7SldIS1Wl.jpg",
      genre_ids: [80, 53],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      popularity: 499.713,
      poster_path: "/mWV2fNBkSTW67dIotVTXDYZhNBj.jpg",
      release_date: "2024-07-31",
      title: "Trap",
      video: false,
      vote_average: 6.376,
      vote_count: 149,
    },
    {
      adult: false,
      backdrop_path: "/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg",
      genre_ids: [16, 28, 18],
      id: 1104844,
      original_language: "ja",
      original_title: "劇場版ブルーロック -EPISODE 凪-",
      overview:
        "One day, Nagi Seishiro receives an invitation to the mysterious BLUE LOCK Project. What awaits him there is an encounter with the finest strikers assembled from across the country. Nagi's dream of becoming the best, alongside Mikage Reo, will take this prodigy to a world he's never known.",
      popularity: 464.859,
      poster_path: "/ae434jM5NG2kKX1rRkG5giMhpPI.jpg",
      release_date: "2024-04-19",
      title: "BLUE LOCK THE MOVIE -EPISODE NAGI-",
      video: false,
      vote_average: 8.466,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      genre_ids: [28, 878, 12, 35],
      id: 365177,
      original_language: "en",
      original_title: "Borderlands",
      overview:
        "Returning to her home planet, an infamous outlaw forms an unexpected alliance with a team of unlikely heroes. Together, they battle alien monsters and dangerous bandits to find a missing girl who holds the key to unimaginable power.",
      popularity: 451.263,
      poster_path: "/lrlSOlTiIlTQqVqJGW4HaWjJaBJ.jpg",
      release_date: "2024-08-07",
      title: "Borderlands",
      video: false,
      vote_average: 5.373,
      vote_count: 51,
    },
  ],
  total_pages: 167,
  total_results: 3339,
};
